version: '3.8'

services:
  nllb-api:
    build:
      context: https://github.com/winstxnhdw/nllb-api.git
      dockerfile: Dockerfile.cuda-build
    environment:
      - SERVER_PORT=7860
      - OMP_NUM_THREADS=6
      - WORKER_COUNT=1
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]